# Generated by Django 3.0.5 on 2022-06-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=120)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=350)),
                ('giturl', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Company'),
        ),
    ]
