# Generated by Django 3.0.5 on 2022-07-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
